- name: Allow http/https
  command: firewall-cmd --zone=public --permanent --add-port=8000-9000/tcp --add-port=8000-9000/udp

- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: "'con01' not in inventory_hostname_short"